### ISSUE TITLE
Tiny unreadable text in the description in some of the tagger items

### ISSUE THREAD

**Issue by art-jimmy** [American-Retail-Technologies/Mickey#21]
Repro steps:
The following SKU items have got tiny unreadable text in the description field:
5515R, 55455, 5549, 5546, 5520, 5524, 55211, 5522, 5523

Expected:
Text in reasonable font size

Actual:
Tiny unreadable text

**Comment by art-jimmy** [comment]
### **[Reference to issue no. 7: Tiny unreadable text in description 420481](https://github.com/American-Retail-Technologies/Mickey/issues/7)**

**Comment by l33ttango** [comment]
Fixed
