### ISSUE TITLE
Wrong telephone number in Labelers

### ISSUE THREAD

**Issue by art-jimmy** [American-Retail-Technologies/Mickey#22]
Comments:
Affected items: 1079, 1060, 1050, 1040, 1034, 1030, 1024, 1020, 1018, 1010, 1090

Repro steps:
Pricing & Tagging -> Avery Price Guns (Labelers) -> 1-Line Guns
Scroll down to details box

Expected:
800-426-5708

Actual:
1-8-426-578

**Comment by l33ttango** [comment]
See bug #19

**Comment by art-jimmy** [comment]
I read bug #19, they are belonged to different sku numbers.

**Comment by art-jimmy** [comment]
### **[Reference Issue 19: 0 Zero doesn't transfer](https://github.com/American-Retail-Technologies/Mickey/issues/19)**

**Comment by art-jimmy** [comment]
[`[](url)`](

> url

)

**Comment by art-jimmy** [comment]
Verified as fixed. Closed.
