### ISSUE TITLE
Broken link: Avery 2-Line Guns

### ISSUE THREAD

**Issue by art-jimmy** [American-Retail-Technologies/Mickey#24]
Comments:
Affected items: sku 1605, 1407, 1408

Repro step:
1. Pricing & Tagging -> Avery Price Guns (Labelers) -> 2-Line Guns
2. Click a Labeler gun
3. Scroll down to details box
4. Click the link "Loading Instructions (https://rs6.eporia.com/company_8/Avery%2Dennison%2PB%2216-21.pdf)"
5. A bug is found

Expected:
It re-directs to the PDF file

Actual:
Broken link:
https://rs6.eporia.com/company_8/Avery%2Dennison%2PB%2216-21.pdf
Bad Request - Invalid URL
HTTP Error 400. The request URL is invalid.

**Comment by l33ttango** [comment]
Link no longer broken.
