### ISSUE TITLE
Item 5520D: Broken Link

### ISSUE THREAD

**Issue by art-jimmy** [American-Retail-Technologies/Mickey#27]
Repro steps:
1. Go to item sku: 5520D
2. Scroll down the details box
3. Click the Assembly instruction link (https://rs6.eporia.com/company_/Taggers%2and%2Fasteners.pdf)

Expected:
It re-directs to the PDF file

Actual:
Broken link:
https://rs6.eporia.com/company_8/Taggers*nd%2Fasteners.pdf
Server Error
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.

**Comment by art-jimmy** [comment]
### **[Reference to issue no. 24: Broken link: Avery 2-Line Guns](https://github.com/American-Retail-Technologies/Mickey/issues/24)**

**Comment by l33ttango** [comment]
Link no longer broken!
