### ISSUE TITLE
SKU 5520T is not found on .com site

### ISSUE THREAD

**Issue by art-jimmy** [American-Retail-Technologies/Mickey#4]
Repro Steps: 
1) goto .net site => Home > Pricing > Tagging Fine Taggers > TACH-IT Tagger > Tagger Fine Tach-It
2) copy the sku# 5520T
3) goto .com site => search: 5520T
4) A bug is found

Expected Behavior: .com site shows the details of sku# 5520T
Observed Behavior: .com site prompts: “There are no search results for 5520T. ”

**Comment by surendermohan** [comment]
We copied the data from http://www.americanretailsupply.com/64682/48132/TG-Tacher-Taggers/TG-Tacher-Taggers.html
