### ISSUE TITLE
ARS.net new website not working well. Products are not showing up. Displaying error message.

### ISSUE THREAD

**Issue by farheen-fathima** [American-Retail-Technologies/Mickey#51]
REPO:
1.Open the ARS website.
2.Open a category and search for a product.
Expected:
The product page is displayed.
Observed:
There has been an error processing your request
Exception printing is disabled by default for security reasons.
Error log record number: 549277844499

**Comment by art-jimmy** [comment]
I think this is the same issue with #43, #39.
